class ConstString {
  static String appName = "Clinical Health Care",
      login = "Login",
      loginNow = "Login Now!",
      welcomeText = "Good to see you back, Login Now!",
      registerText = "Come Join Us, Register Now!",
      signup = "Sign Up",
      signupnow = "Sign Up Now!",
      passwordHint = "Enter Your Password...",
      emailHint = "Enter Your Email...",
      nameHint = "Enter Your Full Name...",
      patientNameHint = "Enter patient's Full Name",
      patientEmail = "Enter Patient's Email",
      patientNumber = "Enter Patient's Phone Number",
      patientAddress = "Enter Patietn's address",
      noAccountLabel = "Don't have an account?",
      haveAccountLabel = "Have an account?",
      forgotPWLabel = "Forgot Password?",
      systolicHint = "Enter Systolic Blood Pressure.",
      diastolicHint = "Enter Diastolic Blood Pressure.",
      respiratoryHint = "Enter Respiratory Rate..",
      heartBeatHint = "Enter Heartbeat Rate..",
      bloodOxygenHint = "Enter Blood Oxygen Level..",
      addPatient = "Add Patient",
      addRecord = "Add Record";
}
